export enum SituacaoMedicaoEnum {
    EM_ELABORACAO = 'EM',
    ENVIADA_PARA_CONVENENTE = 'EC',
    EXCLUIDA = 'EXC',
    EM_ATESTE = 'AT',
    ATESTADA = 'ATD',
    ENVIADA_COMPLEMENTACAO_EMPRESA = 'ECE',
    EM_COMPLEMENTACAO_PELA_EMPRESA = 'CE',
    EM_ANALISE_PELO_CONCEDENTE = 'AC',
    ACEITA = 'ACT',
    ENVIADA_COMPLEMENTACAO_CONVENENTE = 'ECC',
    EM_COMPLEMENTACAO_CONVENENTE = 'CC'
  }
  