export enum Role {
  FISCAL_CONVENENTE = 'FISCAL_CONVENENTE',
  GESTOR_CONVENIO_CONVENENTE = 'GESTOR_CONVENIO_CONVENENTE',
  GESTOR_FINANCEIRO_CONVENENTE = 'GESTOR_FINANCEIRO_CONVENENTE',
  OPERADOR_FINANCEIRO_CONVENENTE = 'OPERADOR_FINANCEIRO_CONVENENTE',
  AGENTE_ACOMPANHAMENTO_INSTITUICAO_MANDATARIA = 'AGENTE_ACOMPANHAMENTO_INSTITUICAO_MANDATARIA',
  FISCAL_CONCEDENTE = 'FISCAL_CONCEDENTE',
  GESTOR_CONVENIO_CONCEDENTE = 'GESTOR_CONVENIO_CONCEDENTE',
  GESTOR_FINANCEIRO_CONCEDENTE = 'GESTOR_FINANCEIRO_CONVENENTE',
  OPERACIONAL_CONCEDENTE = 'OPERACIONAL_CONCEDENTE',
  FISCAL_ACOMPANHAMENTO = "FISCAL_ACOMPANHAMENTO",
  TECNICO_TERCEIRO = "TECNICO_TERCEIRO",
  ADMINISTRADOR_SISTEMA = "ADMINISTRADOR_SISTEMA",
  ADMINISTRADOR_SISTEMA_ORGAO_EXTERNO = "ADMINISTRADOR_SISTEMA_ORGAO_EXTERNO"
}
export namespace Role {
  export function valueOf(roleStr: string): Role {
    return (<any>Role)[roleStr];
  }
}
