package br.gov.planejamento.siconv.med.infra.message;

public enum MessageKey {
	
	/**  
	 * FAIXA DE MENSAGENS PARA ACOMPANHAMENTO / CONFIGURACAO - 000 à 299
	**/
	
	//CONTROLE DE ACESSO DE USUARIOS LOGADOS
	ERRO_ACESSO_PERFIL_NAO_AUTORIZADO("err001"),
	ERRO_CREDENCIAL_AUTENTICACAO_INVALIDA("err002"),
	
	//CONCORRENCIA
	ERRO_GERAL_CONCORRENCIA ("err003"),
	
	//CONSULTA CONTRATOS/EMPRESA
	ERRO_EMPRESA_INEXISTENTE("err004"),
	ERRO_PROPOSTA_INEXISTENTE_VRPL ("err005"),	
	ERRO_PROPOSTA_INEXISTENTE_SICONV ("err006"),
	ERRO_PROPOSTA_NAO_MANTIDA_VRPL ("err007"),

	//SALVAR RESPONSAVEL TECNICO / REGISTRO PROFISSIONAL
	ERRO_RESPONSAVEL_TECNICO_JA_EXISTENTE("err008"),
	ERRO_EDITAR_RT_POSSUI_SUBMETA_ASSINADA("err009"),
	ERRO_REGISTRO_PROFISSIONAL_VINCULADO_CONTRATO("err010"),
	ERRO_RESPONSAVEL_TECNICO_PARAMETROS_INVALIDOS("err011"),
	ERRO_REGISTRO_PROFISSIONAL_NAO_CADASTRADO("err012"),
	ERRO_CONTRATO_NAO_ASSOCIADO_A_EXATAMENTE_UM_REGISTRO_PROFISSIONAL("err013"),
	ERRO_REGISTRO_PROFISSIONAL_DUPLICADO_CAU("err014"),
	ERRO_REGISTRO_PROFISSIONAL_DUPLICADO_CREA_UF("err015"),
	ERRO_EDITAR_ART_RRT_INATIVO("err016"),
	ERRO_EDITAR_RT_ART_RRT_CONTRATO_SOCIAL("err017"),
	ITENS_MEDICOES_INEXISTENTES ("err018"),
	ERRO_INATIVAR_RESP_TEC_SOCIAL_INATIVO("err019"),
	ERRO_SUBMETA_NAO_SELECIONADA_PARA_RT_SOCIAL("err020"),
	ERRO_EDITAR_RESP_TEC_INATIVO("err021"),
	ERRO_RT_SOCIAL_SUBMETA_NAO_VINCULADA_CONTRATO("err022"),
	ERRO_ALTERAR_RESPONSAVEL_TECNICO_NAO_ASSOCIADO_CONTRATO("err023"),
	ERRO_RESPONSAVEL_TECNICO_JA_EXISTENTE_INCLUSIVE_INATIVO("err024"),
	ERRO_RESPTECNICOSOCIAL_CADASTRADO_TIPO_DIFERENTE ("err025"),
	
	//EXCLUIR RESPONSAVEL TECNICO / REGISTRO PROFISSIONAL
	ERRO_RESPONSAVEL_TECNICO_SOCIAL_POSSUI_SUBMETA_ASSINADA("err026"),
	ERRO_EXCLUIR_REGISTRO_PROFISSIONAL("err027"),
	ERRO_EXCLUIR_RT_POSSUI_SUBMETA_ASSINADA("err028"),
	ERRO_EXCLUIR_RT_POSSUI_ANOTACAO("err029"),
	
	//INATIVAR ANOTACAO DE REGISTRO DE RT
	ERRO_INATIVAR_ART_RRT_JA_INATIVO("err030"),
	
	//CONSULTAR ANOTACAO DE REGISTRO DE RT
	ERRO_ART_RRT_INEXISTENTE("err031"),
	CONTRATO_RESP_TEC_INEXISTENTE("err032"),
	
	//INCLUIR / ALTERAR ANOTACAO DE REGISTRO DE RT
	ERRO_CTEF_ARRT_NAO_VINCULADO_AO_CONTRATO("err033"),
	ERRO_EDITAR_ART_RRT_SUBMETA_ASSINADA("err034"),
	ERRO_ART_RRT_SUBMETA_NAO_VINCULADA_CONTRATO("err035"),
	ERRO_EDITAR_ART_RRT_CONTRATO_DIFERENTE_ANTERIOR("err036"),
	ERRO_ART_TIPO_DIFERENTE_RT_ASSOCIADO("err037"),
	
	//EXCLUIR ANOTACAO DE REGISTRO DE RT
	ERRO_EXCLUIR_ART_RRT_SUBMETA_ASSINADA("err038"),
	
	//CONSULTAR USUARIO VINCULADO
	CONTRATO_INEXISTENTE ("err039"),
	CONTRATO_EXISTENTE_NAO_VINCULADO("err040"),
	ERRO_RESPTECNICO_CADASTRADO_TIPO_DIFERENTE ("err041"),
	CPF_EXISTENTE_NAO_VINCULADO_EMPRESA("err042"),
	ERRO_CPF_EXISTENTE_SEM_ACESSO_FUNCIONALIDADE("err043"),
	ERRO_RESPONSAVEL_TECNICO_SOCIAL_INEXISTENTE("err044"),
	ERRO_USUARIO_VINCULADO_SEM_PERFIL_FISCAL_CONVENENTE("err045"),
	ERRO_USUARIO_NAO_CADASTRADO_MAIS_BRASIL ("err046"),
	ERRO_USUARIO_NAO_CADASTRADO_SICONV ("err047"),
	ERRO_USUARIO_INATIVO_SICONV ("err061"),
	
	//DOCUMENTO COMPLEMENTAR
	ERRO_LIMITE_NOME_ANEXO_EXCEDIDO("err048"),
    ERRO_TAMANHO_MAXIMO_ANEXO_EXCEDIDO("err049"),
	ERRO_EXTENSAO_ANEXO_INVALIDA("err050"),
	ERRO_DOCUMENTO_COMPLEMENTAR_POSSUI_MEDICAO("err051"),
    ERRO_DOCUMENTO_COMPLEMENTAR_INEXISTENTE("err052"),
    ERRO_DOCUMENTO_COMPLEMENTAR_DATA_EMISSAO_FUTURA("err053"),
    ERRO_DOCUMENTO_COMPLEMENTAR_DATA_MAIOR_IGUAL_EMISSAO("err054"),
    ERRO_DOCUMENTO_COMPLEMENTAR_SUBMETA_NAO_VINCULADA_CONTRATO("err055"),
    ERRO_DOCUMENTO_COMPLEMENTAR_DATA_EMISSAO_MENOR_ASSINATURA("err056"),
    ERRO_EDITAR_DOCUMENTO_COMPLEMENTAR_EXISTE_MEDICAO("err057"),
    ERRO_DOCUMENTO_COMPLEMENTAR_BLOQUEADO ("err058"),
    ITENS_MEDICOES_BM_INEXISTENTES ("err059"),
    ERRO_RESPONSAVEL_TECNICO_INEXISTENTE("err060"),
    
	//PARALISACAO DE OBRA
    ERRO_PARALISACAO_OBRA_INEXISTENTE("err062"),
    ERRO_MANTER_PARALISACAO("err063"),
    ERRO_DATA_INICIO_ANTERIOR_DATA_FIM_ULTIMA_PARALISACAO("err064"),
    ERRO_DATA_INICIO_PARALISACAO_POSTERIOR_DATA_FIM("err065"),
    ERRO_INCLUSAO_EXISTE_PARALISACAO_EM_ABERTO("err066"),
    
    /**  
	 * FAIXA DE MENSAGENS PARA ACOMPANHAMENTO / CONFIGURACAO - 300 à 999
	**/
    //CONSULTAR MEDICAO
	ERRO_MEDICAO_NAO_ENCONTRADA ("err301"),    
	
	//INCLUIR MEDICAO
	ERRO_PARAMETRO_OBRIGATORIO_NAO_INFORMADO ("err302"),
	ERRO_CONTRATO_NAO_CONFIGURADO("err303"),
	ERRO_CONTRATO_TODAS_SUBMETAS_FINALIZADAS_EMPRESA ("err304"),
	ERRO_CONTRATO_POSSUI_MEDICAO_COMPL_EMP_OU_ENVIADA_COMPL_EMP("err305"),
	ERRO_CRIACAO_MEDICAO_QUANDO_JA_EXISTE_EM_ELABORACAO("err306"),
	ERRO_DATA_INICIO_OBRIGATORIA("err307"),
	ERRO_DATA_INICIO_OBJETO_MAIOR_QUE_ATUAL ("err308"),
	ERRO_DATA_INICIO_ANTERIOR_DATA_FIM("err309"),
	ERRO_DATA_INICIO_ANTERIOR_DATA_ASSINATURA_CONTRATO("err310"),
	ERRO_DATA_FIM_MEDICAO_IGUAL_OU_ANTERIOR_DATA_FIM_VIGENCIA_CTEF("err311"),
	ERRO_DATA_INICIO_OBRA_DIFERENTE_DATA_INICIO_MEDICAO("err312"),
	ERRO_DATA_INICIO_MEDICAO_DIFERENTE_DIA_SEGUINTE_MEDICAO_ANTERIOR("err313"),
	
	//ALTERAR MEDICAO
	ERRO_MEDICAO_NAO_PODE_SER_ALTERADA ("err314"),
	ERRO_MEDICAO_BLOQUEADA("err315"),
	
	//ENVIAR MEDICAO
	ERRO_ENVIO_CONVENENTE_MEDICAO_NAO_PERMITIDA ("err316"),
	ERRO_MEDICAO_SEM_SUBMETAS ("err317"),
	ERRO_SUBMETAS_NAO_ASSINADAS ("err318"),
	
	//CANCELAR ENVIO MEDICAO
	ERRO_CANCELAR_ENVIO_SITUACAO_NAO_PREVISTA("err319"),
	
	//EXCLUIR MEDICAO
	ERRO_EXCLUIR_MEDICAO("err320"),
	
	//INICIAR ATESTE
	ERRO_SITUACAO_INVALIDA_PARA_INICIAR_ATESTE ("err321"),
	ERRO_CONTRATO_POSSUI_MEDICAO_COMPL_CONV_OU_ENVIADA_COMPL_CONV ("err322"),
	ERRO_FUNCIONALIDADE_DISPONIVEL_APENAS_PARA_CONVENENTE ("err323"),
	ERRO_MEDICAO_DEVE_SER_AGRUPADA ("err324"),
	ERRO_ATESTE_MEDICAO_NAO_PERMITIDA ("err325"),
	ERRO_INICIAR_ATESTE_MEDICAO_AGRUPADA ("err373"),
	
	//ATESTAR MEDICAO / COMPLEMENTACAO
	ERRO_SUBMETAS_ASSINADAS_EMPRESA_NAO_ASSINADAS_CONVENENTE ("err326"),
	ERRO_SUBMETAS_RASCUNHO_CONVENENTE ("err327"),
	ERRO_SUBMETAS_ACUMULADAS_RASCUNHO_CONVENENTE ("err377"),
	ERRO_SUBMETAS_ACUMULADAS_ASSINADAS_EMPRESA_NAO_ASSINADAS_CONVENENTE ("err328"),
	ERRO_DOC_COMPLEMENTAR_INVALIDO_INEXISTENTE ("err329"),
		
	//CANCELAR ATESTE
	ERRO_CANCELAR_ENVIO_CONCEDENTE_SITUACAO_NAO_PREVISTA("err330"),
	
	
	//INICIAR ANALISE
	ERRO_SITUACAO_INVALIDA_PARA_INICIAR_ANALISE ("err331"),
	ERRO_FUNCIONALIDADE_DISPONIVEL_APENAS_PARA_CONCEDENTE_MANDATARIA ("err332"),
	ERRO_INICIAR_ANALISE_MEDICAO_AGRUPADA ("err374"),
	
	//ACEITAR MEDICAO
	ERRO_ACEITE_MEDICAO_NAO_PERMITIDA ("err333"),
	ERRO_SUBMETAS_ASSINADAS_CONVENENTE_NAO_ASSINADAS_CONCEDENTE_MANDATARIA ("err334"),
	ERRO_SUBMETAS_RASCUNHO_CONCEDENTE_MADATARIA ("err335"),
	ERRO_SUBMETAS_ACUMULADAS_ASSINADAS_CONVENENTE_NAO_ASSINADAS_CONCEDENTE_MANDATARIA ("err336"),
	ERRO_DATA_VISTORIA_EXTRA_INVALIDA("err337"),
	ERRO_CAMPO_SOLICITANTE_VISTORIA_EXTRA_OBRIGATORIO ("err338"),
	
	//CANCELAR ACEITE
	ERRO_CANCELAR_ACEITE_MEDICAO_AGRUPADA("err339"),
	ERRO_CANCELAR_ACEITE_SITUACAO_NAO_PREVISTA("err340"),
	
	//SOLICITAR COMPLEMENTACAO EMPRESA
	ERRO_COMPLEMENTACAO_EMPRESA_NAO_PERMITIDA("err341"),
	ERRO_NECESSARIO_CADASTRAR_PELO_MENOS_UMA_OBSERVACAO ("err342"),

	//CANCELAR SOLICITACAO COMPLEMENTACAO EMPRESA
	ERRO_CANCELAR_ENVIO_PARA_COMPLEMENTACAO_EMPRESA_SITUACAO_NAO_PREVISTA("err343"),

	//INICIAR COMPLEMENTACAO EMPRESA
	ERRO_SITUACAO_INVALIDA_PARA_INICIAR_COMPLEMENTACAO_EMPRESA ("err344"),
	ERRO_COMPLEMENTACAO_MEDICAO_ACUMULADA ("err345"),
	
	//SOLICITAR COMPLEMENTACAO CONVENENTE
	ERRO_COMPLEMENTACAO_MEDICAO_NAO_PERMITIDA ("err346"),

	//CANCELAR SOLICITACAO COMPLEMEMTACAO CONVENENTE
	ERRO_CANCELAR_ENVIO_PARA_COMPLEMENTACAO_CONVENENTE_SITUACAO_NAO_PREVISTA("err347"),

	//INICIAR COMPLEMENTACAO CONVENENTE
	ERRO_SITUACAO_INVALIDA_PARA_INICIAR_COMPLEMENTACAO_CONVENENTE ("err348"),

	//CONSULTAR SUBMETA
	ERRO_SUBMETA_INEXISTENTE ("err349"),

	//SALVAR SUBMETA
	ITEM_MEDICAO_INEXISTENTE ("err350"),
	ERRO_ITEM_MEDICAO_NAO_PERMITE_MUDANCA ("err351"),
	ERRO_MANTER_SUBMETA_MEDICAO_AGRUPADA ("err352"),
	ERRO_FUNCIONALIDADE_DISPONIVEL_APENAS_PARA_EMPRESA ("err353"),
	ERRO_OPERACAO_NAO_PERMITIDA ("err354"),
		
	//ASSINAR SUBMETA
	ERRO_USUARIO_NAO_RESPONSAVEL_SUBMETA("err355"),
	
	//EXCLUIR RASCUNHO SUBMETA
	ERRO_MEDICAO_SITUACAO_DIFERENTE_RASCUNHO("err356"),
	
	//INCLUIR OBSERVACAO
	ERRO_MANTER_OBSERVACAO_MEDICAO_AGRUPADA ("err357"),
	
	//ALTERAR OBSERVACAO
	ERRO_OBSERVACAO_NAO_PODE_SER_EDITADA ("err358"),
	ERRO_OBSERVACAO_NAO_ENCONTRADA("err359"),
	ERRO_ATIVAR_INATIVAR_ANEXO_PERFIL_RESPONSAVEL_NAO_PERMITIDO ("err360"),
	ERRO_ANEXO_INEXISTENTE ("err361"),
	ERRO_ANEXO_ATIVO_ANTERIORMENTE ("err362"),
	ERRO_ANEXO_INATIVO_ANTERIORMENTE ("err363"),
	
	//EXCLUIR OBSERVACAO
	ERRO_OBSERVACAO_NAO_PODE_SER_EXCLUIDA ("err364"),
	
	//REGISTRAR HISTORICO
	ERRO_PENULTIMO_HISTORICO_MEDICAO_NAO_ENCONTRADO("err365"),
	
	//SALVAR SUBMETA BM
	ERRO_ACUMULADO_SERVICO_MAIOR_PLANEJADO("err366"),
	ERRO_ACUMULADO_SERVICO_CONVENENTE_MAIOR_ACUMULADO_SERVICO_EMPRESA("err368"),
	ERRO_QTDE_INFORMADA_OBRIGATORIA("err369"),
	ERRO_ACUMULADO_SERVICO_MEDICAO_POSTERIOR_MAIOR_PLANEJADO("err370"),
	ERRO_ACUMULADO_SERVICO_CONCEDENTE_MAIOR_ACUMULADO_SERVICO_CONVENENTE("err375"),
	ERRO_ACUMULADO_SERVICO_CONVENENTE_MEDICAO_POSTERIOR_MAIOR_ACUMULADO_SERVICO_EMPRESA("err376"),

	//CONSULTAR SUBMETA
	ERRO_MACRO_SERVICO_NAO_CARREGADO ("err367"),
	
	//LISTAR MEDICOES ACUMULADAS
	ERRO_MEDICAO_ACUMULADA ("err371"),
	
	//ENVIAR COMPLEMENTACAO
	ERRO_SUBMETAS_NAO_ASSINADAS_ENVIO_COMPLEMENTACAO ("err372"),
	
	//CRIAR MEDIÇÃO
	ERRO_CRIACAO_MEDICAO_QUANDO_CONTRATO_PARALISADO("err378");
	
	private String value;

    private MessageKey(String value) {
        this.value = value;
    }

    public String value() {
        return value;
    }

    public static MessageKey fromValue(String value) {

        for (MessageKey messagekey : MessageKey.values()) {
            if (messagekey.value().equalsIgnoreCase(value)) {
                return messagekey;
            }
        }

        throw new IllegalArgumentException("Não foi encontrado MessageKey com o valor " + value);
    }
}
