{
 "title": "Módulo Medição (Quarkus)",
 "description": "Conjunto de métricas do módulo Siconv-Medição",
 "tags": [
  "java",
  "microprofile",
  "quarkus"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "ambiente", "query": { "query": "label_values(ambiente)" } },
   { "name": "modulo", "query": "siconv-medicao-backend" },
   {
    "name": "node",
    "query": {
     "query": "label_values(base_thread_count{ambiente=\"$ambiente\",modulo=\"$modulo\"}, node)"
    }
   },
   {
    "name": "slow_methods",
    "query": {
     "query": "query_result(topk(5, max_over_time(base_REST_request_maxTimeDuration_seconds{ambiente=~\"$ambiente\",modulo=~\"$modulo\",node=~\"$node\"}[$__range])))"
    }
   }
  ]
 },
 "panels": [
  { "title": "Quick Facts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Uptime",
   "type": "stat",
   "description": "Displays the uptime of the Java virtual machine",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(base_jvm_uptime_seconds{ambiente=~\"$ambiente\",modulo=~\"$modulo\",node=~\"$node\"})"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "gauge",
   "description": "Usage for the JVM process. 100% means that all CPUs were actively running threads from the JVM",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(base_cpu_processCpuLoad_percent{ambiente=~\"$ambiente\",modulo=~\"$modulo\",node=~\"$node\"})",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "Mem",
   "type": "gauge",
   "description": "Used / max heap memory",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(base_memory_usedHeap_bytes{ambiente=~\"$ambiente\",modulo=~\"$modulo\",node=~\"$node\"}*100/base_memory_maxHeap_bytes{ambiente=~\"$ambiente\",modulo=~\"$modulo\",node=~\"$node\"})",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "Throughput (HTTP)",
   "type": "stat",
   "description": "HTTP stats in selected time range for all instances in a cluster.\n\nPlease mind that response time displayed here is measured inside JVM, it is not full end to end latency your users see, which can be few times bigger.",
   "gridPos": { "h": 3, "w": 5, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "round(sum(increase(base_REST_request_total{ambiente=~\"$ambiente\",modulo=~\"$modulo\",node=~\"$node\"}[$__range])))",
     "legendFormat": "Total requests"
    },
    {
     "expr": "sum(increase(base_REST_request_elapsedTime_seconds{ambiente=~\"$ambiente\",modulo=~\"$modulo\",node=~\"$node\"}[$__range])) / sum(increase(base_REST_request_total{ambiente=~\"$ambiente\",modulo=~\"$modulo\",node=~\"$node\"}[$__range]))",
     "legendFormat": "Avg response time"
    }
   ]
  },
  {
   "title": "Database Connections",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 7, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(vendor_agroal_active_count{ambiente=~\"$ambiente\",modulo=~\"$modulo\",node=~\"$node\"})",
     "legendFormat": "Active"
    },
    {
     "expr": "sum(vendor_agroal_available_count{ambiente=~\"$ambiente\",modulo=~\"$modulo\",node=~\"$node\"})",
     "legendFormat": "Idle"
    },
    {
     "expr": "sum(vendor_agroal_max_used_count{ambiente=~\"$ambiente\",modulo=~\"$modulo\",node=~\"$node\"})",
     "legendFormat": "Max"
    },
    {
     "expr": "sum(vendor_agroal_leak_detection_count_total{ambiente=~\"$ambiente\",modulo=~\"$modulo\",node=~\"$node\"})",
     "legendFormat": "Leaks"
    },
    {
     "expr": "sum(round(increase(vendor_agroal_acquire_count_total{ambiente=~\"$ambiente\",modulo=~\"$modulo\",node=~\"$node\"}[$__range])))",
     "legendFormat": "Acquire"
    }
   ]
  },
  { "title": "Throughput (HTTP)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Requests per minute",
   "type": "graph",
   "description": "HTTP avg requests/minute",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "round(sum(increase(base_REST_request_total{ambiente=~\"$ambiente\",modulo=~\"$modulo\",node=~\"$node\"}[1m])) by (class, method))",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Avg server response times",
   "type": "graph",
   "description": "HTTP average response times over last [1m].\n\nPlease mind that response time displayed here is measured inside JVM, it is not full end to end latency your users see, which can be few times bigger.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(increase(base_REST_request_elapsedTime_seconds{ambiente=~\"$ambiente\",modulo=~\"$modulo\",node=~\"$node\"}[1m]) / increase(base_REST_request_total{ambiente=~\"$ambiente\",modulo=~\"$modulo\",node=~\"$node\"}[1m]) > 0) by (method, endpoint) ",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Top 5 slow methods",
   "type": "stat",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "base_REST_request_maxTimeDuration_seconds{method=~\"$slow_methods\",ambiente=\"$ambiente\",node=\"$node\"} > 0",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Total requests by class",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 18, "x": 6, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(sum(base_REST_request_total{ambiente=~\"$ambiente\",modulo=~\"$modulo\",node=~\"$node\"}) by(class))",
     "legendFormat": "{{class}}"
    }
   ]
  },
  { "title": "Hardware Consumption", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "CPU Usage",
   "type": "graph",
   "description": "Displays  the \"recent cpu usage\" for the Java Virtual Machine process. This value is a double in the [0.0,1.0] interval. A value of 0.0 means that none of the CPUs were running threads from the JVM process during the recent period of time observed, while a value of 1.0 means that all CPUs were actively running threads from the JVM 100% of the time during the recent period being observed. Threads from the JVM include the application threads as well as the JVM internal threads. All values betweens 0.0 and 1.0 are possible depending of the activities going on in the JVM process and the whole system. If the Java Virtual Machine recent CPU usage is not available, the method returns a negative value.",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(base_cpu_processCpuLoad_percent{ambiente=~\"$ambiente\",modulo=~\"$modulo\",node=~\"$node\"})",
     "legendFormat": "Usage for the JVM process. 100% means that all CPUs were actively running threads from the JVM"
    },
    {
     "expr": "sum(avg_over_time(base_cpu_processCpuLoad_percent{ambiente=~\"$ambiente\",modulo=~\"$modulo\",node=~\"$node\"}[1h]))",
     "legendFormat": "Usage for the JVM process - last hour average"
    },
    {
     "expr": "sum(vendor_cpu_systemCpuLoad_percent{ambiente=~\"$ambiente\",modulo=~\"$modulo\",node=~\"$node\"})",
     "legendFormat": "Usage for the whole system. 100% means that all CPUs were actively running 100% of the time"
    }
   ]
  },
  {
   "title": "System Load",
   "type": "graph",
   "description": "The system load average is the sum of the number of runnable entities queued to the available processors and the number of runnable entities running on the available processors averaged over a period of time. The way in which the load average is calculated is operating system specific but is typically a damped time-dependent average. If the load average is not available, a negative value is displayed. This attribute is designed to provide a hint about the system load and may be queried frequently. The load average may be unavailable on some platforms where it is expensive to implement this method.",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(base_cpu_systemLoadAverage{ambiente=~\"$ambiente\",modulo=~\"$modulo\",node=~\"$node\"})",
     "legendFormat": "System load average for the last minute"
    },
    {
     "expr": "sum(base_cpu_availableProcessors{ambiente=~\"$ambiente\",modulo=~\"$modulo\",node=~\"$node\"})",
     "legendFormat": "Number of processors available to the JVM"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(base_thread_count{ambiente=~\"$ambiente\",modulo=~\"$modulo\",node=~\"$node\"}-base_thread_daemon_count{ambiente=~\"$ambiente\",modulo=~\"$modulo\",node=~\"$node\"})",
     "legendFormat": "Live threads"
    },
    {
     "expr": "sum(base_thread_daemon_count{ambiente=~\"$ambiente\",modulo=~\"$modulo\",node=~\"$node\"})",
     "legendFormat": "Live daemon threads"
    },
    {
     "expr": "sum(base_thread_count{ambiente=~\"$ambiente\",modulo=~\"$modulo\",node=~\"$node\"})",
     "legendFormat": "Live threads total"
    },
    {
     "expr": "sum(base_thread_max_count{ambiente=~\"$ambiente\",modulo=~\"$modulo\",node=~\"$node\"})",
     "legendFormat": "Peak live threads total"
    }
   ]
  },
  {
   "title": "Container Memory",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 23 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(base_memory_maxHeap_bytes{ambiente=~\"$ambiente\",modulo=~\"$modulo\",node=~\"$node\"})",
     "legendFormat": "Max heap"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{ambiente=~\"$ambiente\",modulo=~\"$modulo\",node=~\"$node\"})",
     "legendFormat": "Container working set"
    },
    {
     "expr": "sum(vendor_memory_freeSwapSize_bytes{ambiente=~\"$ambiente\",modulo=~\"$modulo\",node=~\"$node\"})",
     "legendFormat": "Free swap space"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits_memory_bytes{ambiente=~\"$ambiente\",modulo=~\"$modulo\",node=~\"$node\"})",
     "legendFormat": "Container limit"
    }
   ]
  },
  {
   "title": "Process CPU Time",
   "type": "stat",
   "description": "Displays the CPU time used by the process on which the Java virtual machine is running in nanoseconds.",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vendor_cpu_processCpuTime_seconds{ambiente=~\"$ambiente\",modulo=~\"$modulo\",node=~\"$node\"}"
    }
   ]
  },
  { "title": "JVM Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "Heap",
   "type": "graph",
   "description": "Java objects reside in an area called the heap. The heap is created when the JVM starts up and may increase or decrease in size while the application runs. When the heap becomes full, garbage is collected. During the garbage collection objects that are no longer used are cleared, thus making space for new objects.",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(base_memory_usedHeap_bytes{ambiente=~\"$ambiente\",modulo=~\"$modulo\",node=~\"$node\"})",
     "legendFormat": "Used heap memory"
    },
    {
     "expr": "sum(base_memory_committedHeap_bytes{ambiente=~\"$ambiente\",modulo=~\"$modulo\",node=~\"$node\"})",
     "legendFormat": "Memory committed (guaranteed) for the JVM to use"
    },
    {
     "expr": "sum(base_memory_maxHeap_bytes{ambiente=~\"$ambiente\",modulo=~\"$modulo\",node=~\"$node\"})",
     "legendFormat": "Maximum amount (not guaranteed) of heap memory that can be used for memory management"
    }
   ]
  },
  {
   "title": "Heap Memory Pools",
   "type": "graph",
   "description": "Memory Pools are created by JVM memory managers to create a pool of immutable objects. Memory Pool can belong to Heap or Perm Gen, depending on JVM memory manager implementation.",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 33 },
   "repeat": "jvm_memory_pool_heap",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by (name) (vendor_memoryPool_usage_bytes{ambiente=~\"$ambiente\",modulo=~\"$modulo\",node=~\"$node\"})",
     "legendFormat": "Usage {{name}}"
    },
    {
     "expr": "sum by (name) (vendor_memoryPool_usage_max_bytes{ambiente=~\"$ambiente\",modulo=~\"$modulo\",node=~\"$node\"})",
     "legendFormat": "Max {{name}}"
    }
   ]
  },
  {
   "title": "Non-Heap",
   "type": "graph",
   "description": "The JVM has memory other than the heap, referred to as Non-Heap Memory. It is created at the JVM startup and stores per-class structures such as runtime constant pool, field and method data, and the code for methods and constructors, as well as interned Strings. The default maximum size of non-heap memory is 64 MB.",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 33 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(vendor_memory_usedNonHeap_bytes{ambiente=~\"$ambiente\",modulo=~\"$modulo\",node=~\"$node\"})",
     "legendFormat": "Used non-heap memory"
    },
    {
     "expr": "sum(vendor_memory_committedNonHeap_bytes{ambiente=~\"$ambiente\",modulo=~\"$modulo\",node=~\"$node\"})",
     "legendFormat": "Non heap memory committed (guaranteed) for the JVM to use"
    },
    {
     "expr": "sum(vendor_memory_maxNonHeap_bytes{ambiente=~\"$ambiente\",modulo=~\"$modulo\",node=~\"$node\"})",
     "legendFormat": "Maximum amount of used non-heap memory"
    }
   ]
  },
  {
   "title": "Class Loader",
   "type": "graph",
   "description": "Class loaders are responsible for loading Java classes during runtime dynamically to the JVM (Java Virtual Machine). Also, they are part of the JRE (Java Runtime Environment). Hence, the JVM doesn't need to know about the underlying files or file systems in order to run Java programs thanks to class loaders.",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(base_classloader_loadedClasses_count{ambiente=~\"$ambiente\",modulo=~\"$modulo\",node=~\"$node\"})",
     "legendFormat": "Classes currently loaded in the JVM"
    },
    {
     "expr": "sum(delta(base_classloader_loadedClasses_count{ambiente=~\"$ambiente\",modulo=~\"$modulo\",node=~\"$node\"}[1m]))",
     "legendFormat": "Classes currently loaded in the JVM - delta 1m"
    }
   ]
  },
  { "title": "Garbage Collector", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "title": "GC Copy & Mark Sweep Total",
   "type": "graph",
   "description": "Displays the total number of collections that have occurred. This attribute lists -1 if the collection count is undefined for this collector.",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "base_gc_total{ambiente=~\"$ambiente\",modulo=~\"$modulo\",node=~\"$node\"}",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "GC Copy & Mark Sweep Time",
   "type": "graph",
   "description": "Displays the approximate accumulated collection elapsed time in milliseconds. This attribute displays -1 if the collection elapsed time is undefined for this collector. The JVM implementation may use a high resolution timer to measure the elapsed time. This attribute may display the same value even if the collection count has been incremented if the collection elapsed time is very short.",
   "gridPos": { "h": 7, "w": 9, "x": 9, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "base_gc_time_total_seconds{ambiente=~\"$ambiente\",modulo=~\"$modulo\",node=~\"$node\"}",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Total Loaded Class Count",
   "type": "graph",
   "description": "Displays the total number of classes that have been loaded since the Java virtual machine has started execution.",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "base_classloader_loadedClasses_total{ambiente=~\"$ambiente\",modulo=~\"$modulo\",node=~\"$node\"}",
     "legendFormat": "Classes Count"
    }
   ]
  },
  {
   "title": "Collections over last [1m]",
   "type": "graph",
   "description": "JVM garbage collectors summary:\nhttps://www.baeldung.com/jvm-garbage-collectors",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum by (name) (increase(base_gc_total{ambiente=~\"$ambiente\",modulo=~\"$modulo\",node=~\"$node\"}[1m]))",
     "legendFormat": "Number of collections that have occurred last minute ({{name}})"
    }
   ]
  },
  {
   "title": "Durations over last [1m]",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 9, "y": 48 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum by (name) (increase(base_gc_time_total_seconds{ambiente=~\"$ambiente\",modulo=~\"$modulo\",node=~\"$node\"}[1m]))",
     "legendFormat": "Approximate accumulated collection elapsed time ({{name}})"
    }
   ]
  },
  {
   "title": "Total Unloaded Class Count",
   "type": "graph",
   "description": "Displays the total number of classes unloaded since the Java virtual machine has started execution.",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "base_classloader_unloadedClasses_total{ambiente=~\"$ambiente\",modulo=~\"$modulo\",node=~\"$node\"}",
     "legendFormat": "Classes Count"
    }
   ]
  },
  { "title": "Datasource", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 } },
  {
   "title": "Connection pool over last [1m]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(vendor_agroal_active_count{ambiente=~\"$ambiente\",modulo=~\"$modulo\",node=~\"$node\"})",
     "legendFormat": "Active connections"
    },
    {
     "expr": "sum(vendor_agroal_available_count{ambiente=~\"$ambiente\",modulo=~\"$modulo\",node=~\"$node\"})",
     "legendFormat": "Idle connections, available to be acquired"
    },
    {
     "expr": "sum(increase(vendor_agroal_creation_count_total{ambiente=~\"$ambiente\",modulo=~\"$modulo\",node=~\"$node\"}[1m]))",
     "legendFormat": "Created connections in the last minute"
    },
    {
     "expr": "sum(increase(vendor_agroal_destroy_count_total{ambiente=~\"$ambiente\",modulo=~\"$modulo\",node=~\"$node\"}[1m]))",
     "legendFormat": "Destroyed connections last minute"
    },
    {
     "expr": "sum(vendor_agroal_max_used_count{ambiente=~\"$ambiente\",modulo=~\"$modulo\",node=~\"$node\"})",
     "legendFormat": "Maximum number of connections active simultaneously"
    },
    {
     "expr": "sum(increase(vendor_agroal_leak_detection_count_total{ambiente=~\"$ambiente\",modulo=~\"$modulo\",node=~\"$node\"}[1m]))",
     "legendFormat": "Leak detections"
    }
   ]
  },
  {
   "title": "Timing over last [1m]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(vendor_agroal_blocking_time_total_seconds{ambiente=~\"$ambiente\",modulo=~\"$modulo\",node=~\"$node\"}[1m]))",
     "legendFormat": "Time to acquire a connection"
    },
    {
     "expr": "sum(rate(vendor_agroal_creation_time_total_seconds{ambiente=~\"$ambiente\",modulo=~\"$modulo\",node=~\"$node\"}[1m]))",
     "legendFormat": "Time to create a connection"
    },
    {
     "expr": "avg(increase(application_db_query_elapsedTime_seconds{ambiente=~\"$ambiente\",modulo=~\"$modulo\",node=~\"$node\"}[1m]) / increase(application_db_query_total{ambiente=~\"$ambiente\",modulo=~\"$modulo\",node=~\"$node\"}[1m])) by (group, operation)",
     "legendFormat": "Sql: {{group}} {{operation}}"
    }
   ]
  },
  { "title": "Integrations Overhead", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 64 } },
  {
   "title": "GRPC invocations per minute",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 65 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(application_br_gov_planejamento_siconv_med_integration_contratos_ContratosGrpcConsumer_consultarContratoPorId_total{ambiente=~\"$ambiente\", modulo=~\"$modulo\", node=~\"$node\"}[1m])",
     "legendFormat": "consultarContratoPorId"
    },
    {
     "expr": "rate(application_br_gov_planejamento_siconv_med_integration_contratos_ContratosGrpcConsumer_consultarQtdeContratosAptosPorEmpresa_total{ambiente=~\"$ambiente\", modulo=~\"$modulo\", node=~\"$node\"}[1m])",
     "legendFormat": "consultarQtdeContratosAptosPorEmpresa"
    },
    {
     "expr": "rate(application_br_gov_planejamento_siconv_med_integration_contratos_ContratosGrpcConsumer_listarContratosAptosPorEmpresa_total{ambiente=~\"$ambiente\", modulo=~\"$modulo\", node=~\"$node\"}[1m])",
     "legendFormat": "listarContratosAptosPorEmpresa"
    },
    {
     "expr": "rate(application_br_gov_planejamento_siconv_med_integration_contratos_ContratosGrpcConsumer_listarSubmetasPorContratoId_total{ambiente=~\"$ambiente\", modulo=~\"$modulo\", node=~\"$node\"}[1m])",
     "legendFormat": "listarSubmetasPorContratoId"
    },
    {
     "expr": "rate(application_br_gov_planejamento_siconv_med_integration_contratos_ContratosGrpcConsumer_consultarTipoInstrumentoConvenente_total{ambiente=~\"$ambiente\", modulo=~\"$modulo\", node=~\"$node\"}[1m])",
     "legendFormat": "consultarTipoInstrumentoConvenente"
    },
    {
     "expr": "rate(application_br_gov_planejamento_siconv_med_integration_maisbrasil_MaisBrasilGRPCConsumer_consultaUsuarioMaisBrasil_total{ambiente=~\"$ambiente\", modulo=~\"$modulo\", node=~\"$node\"}[1m])",
     "legendFormat": "consultaUsuarioMaisBrasil"
    },
    {
     "expr": "rate(application_br_gov_planejamento_siconv_med_integration_maisbrasil_MaisBrasilGRPCConsumer_listarEmpresasVinculadasMaisBrasilPorCpf_total{ambiente=~\"$ambiente\", modulo=~\"$modulo\", node=~\"$node\"}[1m])",
     "legendFormat": "listarEmpresasVinculadasMaisBrasilPorCpf"
    },
    {
     "expr": "rate(application_br_gov_planejamento_siconv_med_integration_maisbrasil_MaisBrasilGRPCConsumer_consultarEmpresaPorCnpj_total{ambiente=~\"$ambiente\", modulo=~\"$modulo\", node=~\"$node\"}[1m])",
     "legendFormat": "consultarEmpresaPorCnpj"
    },
    {
     "expr": "rate(application_br_gov_planejamento_siconv_med_integration_maisbrasil_MaisBrasilGRPCConsumer_consultarEmpresaPorId_total{ambiente=~\"$ambiente\", modulo=~\"$modulo\", node=~\"$node\"}[1m])",
     "legendFormat": "consultarEmpresaPorId"
    },
    {
     "expr": "rate(application_br_gov_planejamento_siconv_med_integration_projetobasico_ProjetoBasicoGRPCConsumer_consultarDocumentosComplementaresProjetoBasico_total{ambiente=~\"$ambiente\", modulo=~\"$modulo\", node=~\"$node\"}[1m])",
     "legendFormat": "consultarDocumentosComplementaresProjetoBasico"
    },
    {
     "expr": "rate(application_br_gov_planejamento_siconv_med_integration_siconv_SiconvGRPCConsumer_consultarUsuarioMembroAtivoConvenio_total{ambiente=~\"$ambiente\", modulo=~\"$modulo\", node=~\"$node\"}[1m])",
     "legendFormat": "consultarUsuarioMembroAtivoConvenio"
    },
    {
     "expr": "rate(application_br_gov_planejamento_siconv_med_integration_siconv_SiconvGRPCConsumer_consultarUsuarioPorCpf_total{ambiente=~\"$ambiente\", modulo=~\"$modulo\", node=~\"$node\"}[1m])",
     "legendFormat": "consultarUsuarioPorCpf"
    },
    {
     "expr": "rate(application_br_gov_planejamento_siconv_med_integration_siconv_SiconvGRPCConsumer_getIdConvenio_total{ambiente=~\"$ambiente\", modulo=~\"$modulo\", node=~\"$node\"}[1m])",
     "legendFormat": "getIdConvenio"
    },
    {
     "expr": "rate(application_br_gov_planejamento_siconv_med_integration_siconv_SiconvGRPCConsumer_isVRPLResponsavelAceiteProcessoExecucao_total{ambiente=~\"$ambiente\", modulo=~\"$modulo\", node=~\"$node\"}[1m])",
     "legendFormat": "isVRPLResponsavelAceiteProcessoExecucao"
    },
    {
     "expr": "rate(application_br_gov_planejamento_siconv_med_integration_vrpl_VrplGRPCConsumer_consultarListaSubmetasProjetoBasico_total{ambiente=~\"$ambiente\", modulo=~\"$modulo\", node=~\"$node\"}[1m])",
     "legendFormat": "consultarListaSubmetasProjetoBasico"
    },
    {
     "expr": "rate(application_br_gov_planejamento_siconv_med_integration_vrpl_VrplGRPCConsumer_getListaSubmetasPorId_total{ambiente=~\"$ambiente\", modulo=~\"$modulo\", node=~\"$node\"}[1m])",
     "legendFormat": "getListaSubmetasPorId"
    },
    {
     "expr": "rate(application_br_gov_planejamento_siconv_med_integration_vrpl_VrplGRPCConsumer_getSubmetaPorId_total{ambiente=~\"$ambiente\", modulo=~\"$modulo\", node=~\"$node\"}[1m])",
     "legendFormat": "getSubmetaPorId"
    },
    {
     "expr": "rate(application_br_gov_planejamento_siconv_med_integration_vrpl_VrplGRPCConsumer_consultarSubmetasPropostaVRPLAceita_total{ambiente=~\"$ambiente\", modulo=~\"$modulo\", node=~\"$node\"}[1m])",
     "legendFormat": "consultarSubmetasPropostaVRPLAceita"
    }
   ]
  },
  {
   "title": "Avg GRPC invocations time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(application_br_gov_planejamento_siconv_med_integration_contratos_ContratosGrpcConsumer_consultarContratoPorId_elapsedTime_seconds{ambiente=~\"$ambiente\", modulo=~\"$modulo\", node=~\"$node\"}[1m]) / rate(application_br_gov_planejamento_siconv_med_integration_contratos_ContratosGrpcConsumer_consultarContratoPorId_total{ambiente=~\"$ambiente\", modulo=~\"$modulo\", node=~\"$node\"}[1m])",
     "legendFormat": "consultarContratoPorId"
    },
    {
     "expr": "rate(application_br_gov_planejamento_siconv_med_integration_contratos_ContratosGrpcConsumer_consultarQtdeContratosAptosPorEmpresa_elapsedTime_seconds{ambiente=~\"$ambiente\", modulo=~\"$modulo\", node=~\"$node\"}[1m]) / rate(application_br_gov_planejamento_siconv_med_integration_contratos_ContratosGrpcConsumer_consultarQtdeContratosAptosPorEmpresa_total{ambiente=~\"$ambiente\", modulo=~\"$modulo\", node=~\"$node\"}[1m])",
     "legendFormat": "consultarQtdeContratosAptosPorEmpresa"
    },
    {
     "expr": "rate(application_br_gov_planejamento_siconv_med_integration_contratos_ContratosGrpcConsumer_listarContratosAptosPorEmpresa_elapsedTime_seconds{ambiente=~\"$ambiente\", modulo=~\"$modulo\", node=~\"$node\"}[1m]) / rate(application_br_gov_planejamento_siconv_med_integration_contratos_ContratosGrpcConsumer_listarContratosAptosPorEmpresa_total{ambiente=~\"$ambiente\", modulo=~\"$modulo\", node=~\"$node\"}[1m])",
     "legendFormat": "listarContratosAptosPorEmpresa"
    },
    {
     "expr": "rate(application_br_gov_planejamento_siconv_med_integration_contratos_ContratosGrpcConsumer_listarSubmetasPorContratoId_elapsedTime_seconds{ambiente=~\"$ambiente\", modulo=~\"$modulo\", node=~\"$node\"}[1m]) / rate(application_br_gov_planejamento_siconv_med_integration_contratos_ContratosGrpcConsumer_listarSubmetasPorContratoId_total{ambiente=~\"$ambiente\", modulo=~\"$modulo\", node=~\"$node\"}[1m])",
     "legendFormat": "listarSubmetasPorContratoId"
    },
    {
     "expr": "rate(application_br_gov_planejamento_siconv_med_integration_contratos_ContratosGrpcConsumer_consultarTipoInstrumentoConvenente_elapsedTime_seconds{ambiente=~\"$ambiente\", modulo=~\"$modulo\", node=~\"$node\"}[1m]) / rate(application_br_gov_planejamento_siconv_med_integration_contratos_ContratosGrpcConsumer_consultarTipoInstrumentoConvenente_total{ambiente=~\"$ambiente\", modulo=~\"$modulo\", node=~\"$node\"}[1m])",
     "legendFormat": "consultarTipoInstrumentoConvenente"
    },
    {
     "expr": "rate(application_br_gov_planejamento_siconv_med_integration_maisbrasil_MaisBrasilGRPCConsumer_consultaUsuarioMaisBrasil_elapsedTime_seconds{ambiente=~\"$ambiente\", modulo=~\"$modulo\", node=~\"$node\"}[1m]) / rate(application_br_gov_planejamento_siconv_med_integration_maisbrasil_MaisBrasilGRPCConsumer_consultaUsuarioMaisBrasil_total{ambiente=~\"$ambiente\", modulo=~\"$modulo\", node=~\"$node\"}[1m])",
     "legendFormat": "consultaUsuarioMaisBrasil"
    },
    {
     "expr": "rate(application_br_gov_planejamento_siconv_med_integration_maisbrasil_MaisBrasilGRPCConsumer_listarEmpresasVinculadasMaisBrasilPorCpf_elapsedTime_seconds{ambiente=~\"$ambiente\", modulo=~\"$modulo\", node=~\"$node\"}[1m]) / rate(application_br_gov_planejamento_siconv_med_integration_maisbrasil_MaisBrasilGRPCConsumer_listarEmpresasVinculadasMaisBrasilPorCpf_total{ambiente=~\"$ambiente\", modulo=~\"$modulo\", node=~\"$node\"}[1m])",
     "legendFormat": "listarEmpresasVinculadasMaisBrasilPorCpf"
    },
    {
     "expr": "rate(application_br_gov_planejamento_siconv_med_integration_maisbrasil_MaisBrasilGRPCConsumer_consultarEmpresaPorCnpj_elapsedTime_seconds{ambiente=~\"$ambiente\", modulo=~\"$modulo\", node=~\"$node\"}[1m]) / rate(application_br_gov_planejamento_siconv_med_integration_maisbrasil_MaisBrasilGRPCConsumer_consultarEmpresaPorCnpj_total{ambiente=~\"$ambiente\", modulo=~\"$modulo\", node=~\"$node\"}[1m])",
     "legendFormat": "consultarEmpresaPorCnpj"
    },
    {
     "expr": "rate(application_br_gov_planejamento_siconv_med_integration_maisbrasil_MaisBrasilGRPCConsumer_consultarEmpresaPorId_elapsedTime_seconds{ambiente=~\"$ambiente\", modulo=~\"$modulo\", node=~\"$node\"}[1m]) / rate(application_br_gov_planejamento_siconv_med_integration_maisbrasil_MaisBrasilGRPCConsumer_consultarEmpresaPorId_total{ambiente=~\"$ambiente\", modulo=~\"$modulo\", node=~\"$node\"}[1m])",
     "legendFormat": "consultarEmpresaPorId"
    },
    {
     "expr": "rate(application_br_gov_planejamento_siconv_med_integration_projetobasico_ProjetoBasicoGRPCConsumer_consultarDocumentosComplementaresProjetoBasico_elapsedTime_seconds{ambiente=~\"$ambiente\", modulo=~\"$modulo\", node=~\"$node\"}[1m]) / rate(application_br_gov_planejamento_siconv_med_integration_projetobasico_ProjetoBasicoGRPCConsumer_consultarDocumentosComplementaresProjetoBasico_total{ambiente=~\"$ambiente\", modulo=~\"$modulo\", node=~\"$node\"}[1m])",
     "legendFormat": "consultarDocumentosComplementaresProjetoBasico"
    },
    {
     "expr": "rate(application_br_gov_planejamento_siconv_med_integration_siconv_SiconvGRPCConsumer_consultarUsuarioMembroAtivoConvenio_elapsedTime_seconds{ambiente=~\"$ambiente\", modulo=~\"$modulo\", node=~\"$node\"}[1m]) / rate(application_br_gov_planejamento_siconv_med_integration_siconv_SiconvGRPCConsumer_consultarUsuarioMembroAtivoConvenio_total{ambiente=~\"$ambiente\", modulo=~\"$modulo\", node=~\"$node\"}[1m])",
     "legendFormat": "consultarUsuarioMembroAtivoConvenio"
    },
    {
     "expr": "rate(application_br_gov_planejamento_siconv_med_integration_siconv_SiconvGRPCConsumer_consultarUsuarioPorCpf_elapsedTime_seconds{ambiente=~\"$ambiente\", modulo=~\"$modulo\", node=~\"$node\"}[1m]) / rate(application_br_gov_planejamento_siconv_med_integration_siconv_SiconvGRPCConsumer_consultarUsuarioPorCpf_total{ambiente=~\"$ambiente\", modulo=~\"$modulo\", node=~\"$node\"}[1m])",
     "legendFormat": "consultarUsuarioPorCpf"
    },
    {
     "expr": "rate(application_br_gov_planejamento_siconv_med_integration_siconv_SiconvGRPCConsumer_getIdConvenio_elapsedTime_seconds{ambiente=~\"$ambiente\", modulo=~\"$modulo\", node=~\"$node\"}[1m]) / rate(application_br_gov_planejamento_siconv_med_integration_siconv_SiconvGRPCConsumer_getIdConvenio_total{ambiente=~\"$ambiente\", modulo=~\"$modulo\", node=~\"$node\"}[1m])",
     "legendFormat": "getIdConvenio"
    },
    {
     "expr": "rate(application_br_gov_planejamento_siconv_med_integration_siconv_SiconvGRPCConsumer_isVRPLResponsavelAceiteProcessoExecucao_elapsedTime_seconds{ambiente=~\"$ambiente\", modulo=~\"$modulo\", node=~\"$node\"}[1m]) / rate(application_br_gov_planejamento_siconv_med_integration_siconv_SiconvGRPCConsumer_isVRPLResponsavelAceiteProcessoExecucao_total{ambiente=~\"$ambiente\", modulo=~\"$modulo\", node=~\"$node\"}[1m])",
     "legendFormat": "isVRPLResponsavelAceiteProcessoExecucao"
    },
    {
     "expr": "rate(application_br_gov_planejamento_siconv_med_integration_vrpl_VrplGRPCConsumer_consultarListaSubmetasProjetoBasico_elapsedTime_seconds{ambiente=~\"$ambiente\", modulo=~\"$modulo\", node=~\"$node\"}[1m]) / rate(application_br_gov_planejamento_siconv_med_integration_vrpl_VrplGRPCConsumer_consultarListaSubmetasProjetoBasico_total{ambiente=~\"$ambiente\", modulo=~\"$modulo\", node=~\"$node\"}[1m])",
     "legendFormat": "consultarListaSubmetasProjetoBasico"
    },
    {
     "expr": "rate(application_br_gov_planejamento_siconv_med_integration_vrpl_VrplGRPCConsumer_getListaSubmetasPorId_elapsedTime_seconds{ambiente=~\"$ambiente\", modulo=~\"$modulo\", node=~\"$node\"}[1m]) / rate(application_br_gov_planejamento_siconv_med_integration_vrpl_VrplGRPCConsumer_getListaSubmetasPorId_total{ambiente=~\"$ambiente\", modulo=~\"$modulo\", node=~\"$node\"}[1m])",
     "legendFormat": "getListaSubmetasPorId"
    },
    {
     "expr": "rate(application_br_gov_planejamento_siconv_med_integration_vrpl_VrplGRPCConsumer_getSubmetaPorId_elapsedTime_seconds{ambiente=~\"$ambiente\", modulo=~\"$modulo\", node=~\"$node\"}[1m]) / rate(application_br_gov_planejamento_siconv_med_integration_vrpl_VrplGRPCConsumer_getSubmetaPorId_total{ambiente=~\"$ambiente\", modulo=~\"$modulo\", node=~\"$node\"}[1m])",
     "legendFormat": "getSubmetaPorId"
    },
    {
     "expr": "rate(application_br_gov_planejamento_siconv_med_integration_vrpl_VrplGRPCConsumer_consultarSubmetasPropostaVRPLAceita_elapsedTime_seconds{ambiente=~\"$ambiente\", modulo=~\"$modulo\", node=~\"$node\"}[1m]) / rate(application_br_gov_planejamento_siconv_med_integration_vrpl_VrplGRPCConsumer_consultarSubmetasPropostaVRPLAceita_total{ambiente=~\"$ambiente\", modulo=~\"$modulo\", node=~\"$node\"}[1m])",
     "legendFormat": "consultarSubmetasPropostaVRPLAceita"
    },
    {
     "expr": "rate(application_br_gov_planejamento_siconv_med_integration_vrpl_VrplGRPCConsumer_consultarListaSubmetasProjetoBasico_elapsedTime_seconds{ambiente=~\"$ambiente\", modulo=~\"$modulo\", node=~\"$node\"}[1m]) / rate(application_br_gov_planejamento_siconv_med_integration_vrpl_VrplGRPCConsumer_consultarListaSubmetasProjetoBasico_total{ambiente=~\"$ambiente\", modulo=~\"$modulo\", node=~\"$node\"}[1m])",
     "legendFormat": "consultarListaSubmetasProjetoBasico"
    }
   ]
  }
 ]
}