global:
  scrape_interval:     5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 1s
    metrics_path: /metrics
    static_configs:
      - targets:
        - localhost:8080
    relabel_configs:
        # source label must be one that exists, so use __address__
      - source_labels: [__address__]
        # target label is the one you want to create
        target_label: ambiente
        replacement: "local"
      - source_labels: [__address__]
        # target label is the one you want to create
        target_label: modulo
        replacement: "siconv-medicao-backend"
      - source_labels: [__address__]
        # target label is the one you want to create
        target_label: node
        replacement: "local"

